skin_list = [
    ("1", "img/type1.svg", "Type I", "Extremely Sensitive skin, Pale skinned", 80, 100),
    ("2", "img/type2.svg", "Type II", "Very sensitive skin, Light skinned", 80, 100),
    ("3", "img/type3.svg", "Type III", "Sensitive skin, Creamy-white skinned", 80, 100),
    ("4", "img/type4.svg", "Type IV", "Mildly sensitive skin, Olive skin", 80, 100),
    ("5", "img/type5.svg", "Type V", "Dark-brown skin", 80, 100),
    ("6", "img/type6.svg", "Type VI", "Deeply-pigmented skin", 80, 100),
]

ocd_key = "2fde3b09724c497a9a14e435c519790c"
default_location = "Trinity College Dublin"
default_coordinates = ("53.343792", "-6.254572")

openmeteo_url = "https://api.open-meteo.com/v1/forecast"

body_surface_area = {
    "birth": {
        "head": 19,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 5.5,
        "left_leg_lower": 5,
        "left_feet": 3.5,
        "right_leg_upper": 5.5,
        "right_leg_lower": 5,
        "right_feet": 3.5,
    },
    "1-4": {
        "head": 17,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 6.5,
        "left_leg_lower": 5,
        "left_feet": 3.5,
        "right_leg_upper": 6.5,
        "right_leg_lower": 5,
        "right_feet": 3.5,
    },
    "5-9": {
        "head": 13,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 8,
        "left_leg_lower": 5.5,
        "left_feet": 3.5,
        "right_leg_upper": 8,
        "right_leg_lower": 5.5,
        "right_feet": 3.5,
    },
    "10-14": {
        "head": 11,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 8.5,
        "left_leg_lower": 6,
        "left_feet": 3.5,
        "right_leg_upper": 8.5,
        "right_leg_lower": 6,
        "right_feet": 3.5,
    },
    "15": {
        "head": 9,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 9,
        "left_leg_lower": 6.5,
        "left_feet": 3.5,
        "right_leg_upper": 9,
        "right_leg_lower": 6.5,
        "right_feet": 3.5,
    },
    "adult": {
        "head": 7,
        "neck": 2,
        "left_arm_upper": 4,
        "left_arm_lower": 3,
        "left_palm": 2.5,
        "right_arm_upper": 4,
        "right_arm_lower": 3,
        "right_palm": 2.5,
        "torso": 26,
        "left_leg_upper": 9.5,
        "left_leg_lower": 7,
        "left_feet": 3.5,
        "right_leg_upper": 9.5,
        "right_leg_lower": 7,
        "right_feet": 3.5,
    },
}

med = {
    "1": 200,
    "2": 250,
    "3": 300,
    "4": 450,
    "5": 600,
    "6": 1000,
}

dynamodb_table = "dsure"
